### ISSUE TITLE
VirtualScrollPicker is never actually exposed

### ISSUE THREAD

**Issue by lyle45** [serebrov/emoji-mart-vue#120]
VirtualScrollPicker is never actually exposed only declared, so you can't import and use it.

**Comment by serebrov** [comment]
@lyle45 I am actually trying to get rid of `VirtualScrollPicker` in favor of `Picker`. It did not give a lot of performance improvement, but created quite a lot of problems (see #80).

So I first switched to `Picker` as a default component and removed `VirtualScrollPicker` from exports in the last update.
It is not complex to add it back to exports, but the problem is that I did not port all the recent accessibility and keyboard control changes from #106 to the `VirtualScrollPicker` component, so it would be lacking some features.

Do you find `VirtualScrollPicker` to be useful (better than `Picker`)?

In general, if you need it for some specific use case, you can also use its source as an example, all other components are exported and can be used as building blocks to componse your own picker.

**Comment by lyle45** [comment]
@serebrov Understand your problem

Do you have an example on how to integrate the default picker with a virtual scroller (currently performance is not good :\ )
For e.g. how to integrate the emoji list with Quasars virtual scroller?

https://quasar.dev/vue-components/virtual-scroll

**Comment by serebrov** [comment]
@lyle45 I think you can do `import VirtualScrollPicker from "emoji-mart-vue-fast/src/components/VirtualScrollPicker"` to get the `VirtualScrollPicker`.

As for the example - the component [code itself](https://github.com/serebrov/emoji-mart-vue/blob/0ebc0c8d7a53111f1218edcdf2be09d261d60fe3/src/components/VirtualScrollPicker.vue) can be used as an example of composing the picker from other components.

The [Picker component](https://github.com/serebrov/emoji-mart-vue/blob/0ebc0c8d7a53111f1218edcdf2be09d261d60fe3/src/components/Picker.vue) is similar, but with keyboard support.

Also, could you share more observations on the performance? How do you measure the performance and in which scenario you see the virtual scroller advantage?

**Comment by skjnldsv** [comment]
I guess you can close since it got removed https://github.com/serebrov/emoji-mart-vue/pull/241
