### ISSUE TITLE
Not working when want to use only messenger icon data

### ISSUE THREAD

**Issue by xibman** [serebrov/emoji-mart-vue#55]
Hi,

i try to only use messenger data but it fail.

```
import data from 'emoji-mart-vue-fast/data/messenger.json'
import { Picker, EmojiIndex } from 'emoji-mart-vue-fast'
import 'emoji-mart-vue-fast/css/emoji-mart.css'
let emojiIndex = new EmojiIndex(data)
```

And the template

```
<template>
  <Picker
    set="messenger"
    :data="emojiIndex"
  />
</template>
```

No error in console but nothing displayed in the picker

**Comment by serebrov** [comment]
@xibman Thanks for reporting and for the example, I am able to reproduce the issue and will work on a fix.

This is related to what we discussed with @cavincavin in #53: same issue with empty picker when only using `messenger.json` data. I have a [demo](https://serebrov.github.io/emoji-mart-vue-fast-min-app/) that works with `messenger.json` data, but I now see that this is because it uses the "native" set, when switched to "messenger" set, it also displays no emojis.

Also confirmed that this was a bug on 5.x versions, so not related to the change in #53.
And the issue is reproduced with any other set (`apple.json`, `google.json`, etc)

**Comment by serebrov** [comment]
@xibman I fixed the issue in version `6.0.1`, please check if it works for you.

Also updated the minimal [demo app](https://serebrov.github.io/emoji-mart-vue-fast-min-app/), [source](https://github.com/serebrov/emoji-mart-vue-fast-min-app), the new version fixed the issue in demo.

**Comment by cavincavin** [comment]
@serebrov  Thank you for this fix.

**Comment by xibman** [comment]
@serebrov Thanks a lot it work perfectly now !!
