### ISSUE TITLE
Updated emoji set

### ISSUE THREAD

**Issue by cxy8686** [serebrov/emoji-mart-vue#62]
Will this project be updated with the newest emojis that include bald and red head emojis?

**Comment by serebrov** [comment]
Probably at some point it will, that depends on the `emoji-datasource` npm package which is an origin of all the emoji data. As I see from the [readme](https://github.com/iamcal/emoji-data) it only has v11 emoji at the moment.

And, as I understand, you want new emojis added in v12 (or [12.1](https://unicode.org/emoji/charts/emoji-released.html)).

**Comment by ram-you** [comment]
Hi @serebrov , please update emoji-datasource to latest (v5.0.1)  that comes with a lot of new stuff:
 * Updated to Unicode v12.1
 * Updated Apple images to macOS 10.15.1
 * Updated Twemoji images to v12.1.4
 * Updated Android images to v2019-11-19-unicode12
 * Updated Facebook images to v9 / EMOJI_3
 * **Removed Messenger images (now unified with Facebook)**
 * Changed the `added_in` field to specify Emoji spec version rather than Unicode version (the underlying Unicode data changed)
 * Support for emoji with multiple skin tones within a single emoji 

Thanks again for your great work.

**Comment by serebrov** [comment]
Preparing an update, will up major version (v6 -> v7) as there are some breaking changes:

- Removed 'emojione' set (removed from [emoji-datasource](https://github.com/iamcal/emoji-data) by [JoyPixels request](https://github.com/iamcal/emoji-data/blob/master/CHANGES.md#2018-07-05--v410))
- Removed 'messenger' set - it was [merged](https://github.com/iamcal/emoji-data/blob/master/CHANGES.md#2020-01-10--v500) into 'facebook' set
- Changed emoji categories: removed 'Smileys & People', added 'Smileys & Emotions' and 'People & Body' instead

**Comment by serebrov** [comment]
Version `7.0.0` is on npm, new emojis are also in the demo app - https://serebrov.github.io/emoji-mart-vue/.

**Comment by ram-you** [comment]
@serebrov Thank you very much.
