### ISSUE TITLE
code error is `this.include`

### ISSUE THREAD

**Issue by yoonasy** [serebrov/emoji-mart-vue#97]
https://github.com/serebrov/emoji-mart-vue/blob/2d6ec8aeaf0cc29efd936fa68da45521bfd76383/src/components/StaticPicker.vue#L179

Sorry, I didn't find where the `include` came from

**Comment by yoonasy** [comment]
should is props?

**Comment by yoonasy** [comment]
and `this.exclude`
https://github.com/serebrov/emoji-mart-vue/blob/2d6ec8aeaf0cc29efd936fa68da45521bfd76383/src/components/StaticPicker.vue#L183

**Comment by yoonasy** [comment]
https://github.com/serebrov/emoji-mart-vue/blob/master/src/utils/shared-props.js

not found

**Comment by serebrov** [comment]
@yoonasy actually the `include` and `exclude` are properties of the `EmojiIndex` class, not of the component.

So having them used in the `StaticPicker` is definitely a bug, also it should be harmless as `this.include` and `this.exclude` are used in the condition and should always return false.
Are you hitting some issue because of it?

If you just want to actually filter the data, you can use code like this:

```
 <template>
  <StaticPicker :data="indexInclude" />
 </template>

<script>
  const indexInclude = new EmojiIndex(data, {
    include: ['nature', 'smileys', 'recent'],
  })

  export default {
    data() {
      return {
        indexInclude: indexInclude
      }
    },
    components: {
      StaticPicker,
    },
}

</script>
```

See the complete example in the [demo app](https://github.com/serebrov/emoji-mart-vue/blob/2d6ec8aeaf0cc29efd936fa68da45521bfd76383/docs/app.vue#L220-L234).

Note for me: these properties were originally the in the [picker component](https://github.com/jm-david/emoji-mart-vue/blob/master/src/utils/shared-props.js#L96-L101), should be safe to remove.

**Comment by yoonasy** [comment]
thank u, resolved
