### ISSUE TITLE
some twitter emoji can't find right pic from cdn

### ISSUE THREAD

**Issue by luluxia** [serebrov/emoji-mart-vue#98]
![image](https://user-images.githubusercontent.com/29321564/101641896-4a759c00-3a6d-11eb-8d18-a9d427b55952.png)
i use unified code to get twitter emoji's pic, most emoji can work, but a few emoji with '-fe0f' at the end should deleted '-fe0f' to work normally

**Comment by serebrov** [comment]
These codes are coming from the [emoji-datasource library](https://github.com/iamcal/emoji-data) and there are two related properties:

| Fields | Description |
| ------ | ----------- |
| `unified` | The Unicode codepoint, as 4-5 hex digits. Where an emoji needs 2 or more codepoints, they are specified like 1F1EA-1F1F8. For emoji that need to specifiy a variation selector (-FE0F), that is included here. |
| `non_qualified` | For emoji that also have usage without a variation selector, that version is included here (otherwise is null). |

I think you might want to check the `non_qualified` field first and if it is not set then fallback to  the`unified` vale.
Something like `code = emoji_data['non_qualified'] ? emoji_data['non_qualified'] : emoji_data['unified']`.

**Comment by luluxia** [comment]
thank you, i found this emoji datasource used different file naming methods with twitter. in this emoji datasource. i only need use `unified` to get the image.
